Best10/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('items.urls', namespace='items')),
    url(r'^', include('blogs.urls', namespace='blogs')),
    url(r'^', include('landing_page.urls', namespace='landing_page')),
    url(r'^', include('featured_products.urls', namespace='featured-products')),
]

blogs/urls.py
from django.conf.urls import url
from django.contrib import admin
from items import views
from .views import blog_list, blog_detail, testing


urlpatterns = [
    url('^blog/$', blog_list, name='list'),
    url('^blog/(?P<id>\d+)/$', blog_detail, name='detail'),
    url('^blog/test/$', testing, name='testing'),
]

featured_products/urls.py
from django.conf.urls import url
from django.contrib import admin
from items import views
from .views import product_detail


urlpatterns = [
    # url(r'^products/save$', save_product, name='save'),
    url(r'^products/detail/(?P<id>\d+)/$',product_detail, name='product-detail'),
]

items/urls.py
from django.conf.urls import url
from .views import search_result, item_detail


urlpatterns = [
    url(r'^result/$', search_result, name='result'),
    url(r'^items/detail/(?P<id>\d+)/$', item_detail, name='detail'),
]

landing_page/urls.py
from django.conf.urls import url
from django.contrib import admin
from items import views
from .views import about, contact, home


urlpatterns = [
    url(r'^$', home, name='home'),
    url('^about/$', about, name='about'),
    url('^contact/$', contact, name='contact')


]

blogs/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):

    title   = models.CharField(max_length=500)
    content = models.TextField(max_length=10000)
    image   = models.CharField(max_length=100)


    def __str__(self):

        return self.title

featured_products/models.py
from django.db import models

# Create your models here.

class FeatureProduct(models.Model):
    title     = models.CharField(max_length=500)
    link      = models.CharField(max_length=500)
    rating    = models.FloatField()
    rating_count = models.IntegerField()
    image        = models.CharField(max_length=500)
    price        = models.CharField(max_length=500)
    hotscore    = models.IntegerField()
    query_word  = models.CharField(max_length=500, null=True, blank=True)
    goodreads_url = models.CharField(max_length=500, null=True, blank=True)

    def __str__(self):
        return self.title

items/models.py
from django.db import models

# Create your models here.
class SearchItem(models.Model):

    title = models.CharField(max_length=500)
    link  = models.CharField(max_length=500)
    rating = models.FloatField()
    rating_count = models.IntegerField(null=True, blank=True)
    hotscore = models.IntegerField()
    image    = models.CharField(max_length=300, null=True, blank=True)
    price    = models.IntegerField(null=True,blank=True)
    goodreads_url = models.CharField(max_length=300, null=True, blank=True)

    description = models.TextField(max_length=5000, null=True, blank=True)
    query_word = models.CharField(max_length=100, null=True, blank=True)
    price    = models.IntegerField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title

landing_page/models.py
from django.db import models

# Create your models here.

blogs/views.py
from django.shortcuts import render
from .models import Blog
# Create your views here.

def blog_list(request):
    blogs = Blog.objects.all().order_by('-id')

    context = {
        'blogs': blogs
    }

    return render(request, 'blogs/blog_list.html',context)

def blog_detail(request, id):

    blog = Blog.objects.get(id=id)

    context = {
        'blog': blog
    }

    return render(request, 'blogs/blog_detail.html',context)

def testing(request):
    return render(request, 'blogs/testing.html')

featured_products/views.py
from django.shortcuts import render
from items.amazon_models import Item
from .models import FeatureProduct
from items.review_model import Review
# Create your views here.


def product_detail(request, id):
    product = FeatureProduct.objects.get(id=id)
    print(product.link)
    review  = Review()
    reviews = review.parse_reviews(product.link)

    context = {
        'product': product,
        'reviews' : reviews,
    }
    return render(request,'featured_products/product_detail.html', context)

items/views.py
from django.shortcuts import render
from random import randint

from featured_products.models import FeatureProduct
from .models import SearchItem
# Create your views here.
from django.shortcuts import render
from .amazon_models import Item
from .review_model import Review

# Home Page
def search_result(request):

    if request.method == "POST":
        q_word = request.POST['query_word']
        category = request.POST.get('category', None)


        if q_word:
            item = Item()
            search_result = item.get_items(q_word=q_word)
            # save_product(search_result)

            for item in search_result:

                new_item = SearchItem()
                new_item.title = item.title
                new_item.link  = item.link
                new_item.image = item.image
                new_item.rating_count = item.rating_count
                new_item.rating = item.rating
                new_item.hotscore = item.hotscore
                new_item.price    = item.price
                new_item.query_word = q_word

                new_item.goodreads_url = item.goodreads_url

                new_item.save()

            saved_search_result = SearchItem.objects.filter(query_word=q_word)


            context = {

             "item_list": saved_search_result,

            }
            return render(request,'items/search_result.html', context)

        else:
            context = {
                "error" : "Please enter your search items"
            }
            return render(request,'items/search_result.html', context)


    return render(request, 'items/search_result.html')

def item_detail(request, id):
    item = SearchItem.objects.get(id=id)
    print(item.link)

    review = Review()
    reviews = review.parse_reviews(item.link)





    context = {
        'item': item,
        'reviews': reviews,

    }
    return render(request, 'items/item_detail.html', context)





def save_product(item_list):

    for product in item_list:
        featured_product = FeatureProduct()
        featured_product.title = product.title
        featured_product.link  = product.link
        featured_product.image = product.image
        featured_product.rating = product.rating
        featured_product.rating_count = product.rating_count
        featured_product.hotscore     = product.hotscore
        featured_product.price        = product.price

        featured_product.goodreads_url = product.goodreads_url
        featured_product.query_word   = "Programming"
        featured_product.save()

    return FeatureProduct.objects.all()

landing_page/views.py
from django.shortcuts import render
from featured_products.models import FeatureProduct
from datetime import datetime, timedelta
from items.models import SearchItem
# Create your views here.

def home(request):
    featured_products = FeatureProduct.objects.filter(query_word="Startup")
    delete_older_items()

    item_list = []

    if request.method == "GET":
        category = request.GET.get('category')
        if not category:
            category= 'Startup'
        if category:
            featured_products = FeatureProduct.objects.filter(query_word=category)

            context = {
                'featured_products': featured_products,
                'category': category,
            }
            return render(request, 'landing_page/home.html', context)


    return render(request, 'landing_page/home.html',{'featured_products': featured_products})



def delete_older_items():
    time_threshold = datetime.now() - timedelta(minutes=1)
    results = SearchItem.objects.filter(created_at__lt=time_threshold)
    if results:
        print('Deleted ' + str(len(results)) + " old items")
        results.delete()



def about(request):
    return render(request,'landing_page/about.html')

def contact(request):
    return render(request,'landing_page/contact.html')

templates/base.html
<!doctype html>
<html lang="en">
  <head>
      <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-119257461-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-119257461-2');
</script>

      <!-- Hotjar Tracking Code for https://www.best10.store -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:883618,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>


    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href='https://fonts.googleapis.com/css?family=Alike Angular|ABeeZee|Amethysta|Adamina|Alef' rel='stylesheet'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">


  <style>
.content-text {
    font-family: 'Amethysta';font-size: 21px;
    font-weight: lighter;
}
.title-text{
    font-family: 'Alef';
}
.content-bold{
    font-family: 'Amethysta';font-size: 24px;
    font-weight: bold;
}

.top-buffer { margin-top:70px; }


</style>


     {% block seo %}  {% endblock %}

  </head>
  <body>

    {% include 'navbar.html'  %}
    <div class="container">
    {% block content %}
    {% endblock %}
        </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

      <script>
        $(document).ready(function(){
        console.log("jQuery is ready in base");

        });

    </script>

  </body>
</html>

templates/blogs/blog_detail.html
{% extends 'base.html' %}

{% block content%}

<div class="container">
    {{blog.content|safe }}

</div>
{% endblock %}

templates/blogs/blog_list.html
{% extends 'base.html'%}
{% block content %}
<div class="container">
    <br>
    <br>
    <h1 class="title-text">Blogs</h1>
    <hr>
    <div class="row">
        {% for blog in blogs %}
        <div class="col-6">
          {% include 'blogs/card.html' with blog=blog %}
        </div>
           {% endfor %}
    </div>
    <br>
    <hr>

</div>

{% endblock %}

templates/blogs/card.html
 <div class="card text-center border-0">
   <div class="card-body">
       <a href="/blog/{{blog.id}}/">
       <img src="{{blog.image}}" width="500" height="300">
           <br>
           <hr>
           <br>
       <h4 class="text-dark content-text">{{ blog.title }}</h4></a>
   </div>
</div>
 <br>

templates/featured_products/product_card.html
<!-- Search List Session-->
<div class="container-fluid">

    <div class="row">
        <!--<div class="col-2"></div>-->
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-lx-12">
<!--<p class="text-muted">Selected the best 10 results from <b>{{ total_items_number}}</b> related items on Amazon</p>-->
 <!--<p></p>-->
        {% for item in item_list %}
<div class="card">
  <div class="card-header">

      {{ item.title }}

  </div>
  <div class="card-body">

       <p> <span class="float-left badge badge-pill badge-warning" >#{{ forloop.counter}}</span>
           <!--<span class="float-right badge badge-pill badge-warning">Customer satisfaction {{ item.hotscore }}%</span>-->
           <a href="{{ item.link}}&tag=best10store07-20" target="_blank" class="float-right btn btn-outline-info btn-sm">View on Amazon</a>
       </p>
        <br>

        <p class="text-center"><img src="{{ item.image }}" height="100">&ensp;</p>

         <p class="float-left lead"><img src="https://s3-us-west-1.amazonaws.com/a1-language/media/image/rating.png" height="22" width="22">Rating:{{ item.rating }}·Count:{{item.rating_count}} {% if item.price %}·Price:${{ item.price}}{% endif %}</p>
        <a href="/products/detail/{{item.id}}/" target="_blank" class="float-right btn btn-outline-info btn-sm float-right">Get Detail</a>


  </div>
</div>
<br>
{% endfor %}
    </div>
        <!--<div class="col-2"></div>-->
    </div>
</div>

templates/featured_products/product_detail.html
{% extends 'base.html' %}

{% block content%}

<div class="container">
    <br>
    <br>
<div class="jumbotron bg-light">
    <div class="row">
        <div class="col-3">
        <p class="float-left"> <img src="{{ product.image}}" height="200" width="180"></p>
        </div>
        <div class="col-9">
             <h3 class="">{{ product.title }}</h3>
    <hr>
            <p class="lead">Price: ${{ product.price}}</p>
    <span class="btn btn-warning">Rating:{{ product.rating }}</span>
    <span class="btn btn-warning">Count:{{ product.rating_count}}</span>
   <span class="btn btn-warning float-right">Customer satisfaction {{ product.hotscore }}%</span>

    <br>

        <br>
    <hr>
        <a class="btn btn-danger float-left" href="{{ product.link }} " role="button" target="_blank">View on Amazon</a>

        <a class="btn btn-danger float-right" href="{{ product.goodreads_url }} " role="button" target="_blank">View on Goodread</a>


  <!--<p class="lead">{{product.description|force_escape|linebreaks }}</p>-->

        </div>
    </div>
</div>


    <div class="jumbotron jumbotron-fluid bg-light">
  <div class="container">

    <h3 class="title-text">Top customer reviews from Goodreads</h3>
      <br>
{% for review in reviews %}
     <p class="lead">{{ review }}</p>
            <p class="content-text">-by anonymous users from Goodreads</p>
      {% endfor %}
  </div>
    <br>
    </div>


    </div>





<br><br><br><br><br>
{% endblock %}

templates/items/item_card.html
<!-- Search List Session-->
<div class="container-fluid bg-light">


        <div class="row">
        {% for item in item_list %}
                <div class="col-12 col-sm-12 col-md-4 col-lg-4 col-lx-4">

            <div class="card" style="width: 20rem;">





        <div class="card-body">
           <p><span class="float-left badge badge-pill badge-warning" >#{{ forloop.counter}}</span> <span class="card-text">{{ item.title | truncatechars:55 }}</span></p>



       <!--</p>-->
        <p class="text-center"><a href="/items/detail/{{item.id}}/" target="_blank"><img src="{{ item.image }}" height="100"></a></p>
         <p class="card-text"><img src="https://s3-us-west-1.amazonaws.com/a1-language/media/image/rating.png" height="22" width="22">Rating:{{ item.rating }}·Count:{{item.rating_count}} {% if item.price %}·Price:${{ item.price}}{% endif %}</p>

        </div>
</div>
</div>
{% endfor %}


    </div>
</div>

templates/items/item_detail.html
{% include 'featured_products/product_detail.html' with product=item %}

templates/items/item_list.html
{% extends 'base.html' %}


{%block content%}

<style>
 .jumbotron{
    background-color: #FCEFE7;
    }
</style>



<br>
<div class="container">




    <!-- featured_products_list -->
    {% include 'items/item_card.html' with item_list=featured_products %}
    <!-- End Featured Products-->



    <!--{% endif %}-->



     {% include 'items/item_card.html' %}



{% endblock %}

templates/items/jumbotron.html
<!-- Junbotron Area-->
<!--<div class="jumbotron jumbotron-fluid">-->
  <div class="container-fluid text-center search-container">

     <div class="row top-buffer"></div>
      <h1>Find Best 10 Python Books for Beginners</h1>

      <div class="row top-buffer"></div>

          <div class="row">
      <div class="col-6 offset-3">
      <form method="POST" action="/result/"> {% csrf_token %}
      <div class="input-group">
     <input type="text" class="form-control" name="query_word" placeholder="Enter specific keywords...">
     <span class="input-group-btn">
    <button class="btn btn-warning" type="submit">LOOK UP</button>
  </span>
      </div>
</form>

  </div>
  </div>
  </div>
<!--</div>-->

templates/items/search_result.html
{% extends 'base.html' %}

{%block content%}

<style>
 .jumbotron{
    background-color: #FCEFE7;
    }

.search-cards {

   background-color: #FCEFE7;
}

</style>

{% include 'items/jumbotron.html' %}

<br>



{% if error %}
<p class="lead text-center" >{{ error }}</p>
{% endif %}


{% include 'items/item_card.html' %}



{% endblock %}

templates/landing_page/about.html
{% extends 'base.html'%}
{% block content %}
<br><br><br><br><br>
<div class="container">

      <!-- Second Row-->
   <div class="row">
       <div class="col-md-1 col-lg-1 col-lx-1"></div>
     <div class="col-12 col-sm-12 col-md-4 col-lg-4 col-lx-4">
      <img src="https://s3-us-west-1.amazonaws.com/a1-language/media/image/old_way.jpg" height="300" width="300" class="rounded-circle">
    </div>
    <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-lx-6">
      <div class="card border-0">
    <div class="card-body">
    <span class="h4 font-weight-bold">We do the research for you</span><br><br>
    <p class="lead">
    We know how much time you spend to look for a best item. Let us do all the tedious and time-consuming work for you.
    It's time to say goodbye to the old shopping ways
    </p>
    </div>
</div>
    </div>
    <div class="col-md-1 col-lg-1 col-lx-1"></div>
  </div>

    <hr>



  <!-- First Row-->
  <div class="row">
    <div class="col-md-1 col-lg-1 col-lx-1"></div>
      <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-lx-6">
      <div class="card border-0">
    <div class="card-body">
      <br><br><br>
    <span class="h4 font-weight-bold">Easier & faster shopping experience
    </span><br><br>
    <p class="lead">
      We gather all items' information from the Internet and return the best 10 results based on customer satisfaction, reviews, ratings, and popularity
    </p>
    </div>
</div>
    </div>
    <div class="col-12 col-sm-12 col-md-4 col-lg-4 col-lx-4">
      <img src="https://s3-us-west-1.amazonaws.com/a1-language/media/image/shopping_img.jpg" height="300" width="300" class="rounded-circle">
    </div>
      <div class="col-md-1 col-lg-1 col-lx-1"></div>
  </div>
  <br><br>
  <hr>
  <br><br>


</div>



{% endblock %}

templates/landing_page/contact.html
{% extends 'base.html' %}

{% block content %}

<style>
 .jumbotron{
    background-color: #FCEFE7;
    }
</style>



<div class="jumbotron jumbotron-fluid">
  <div class="container" style="height:600px">
      <br><br><br><br><br>

    <h1 class="h3">Are you having any trouble?</h1><br>
    <p class="lead">Please reach out to: best10store.hub@gmail.com</p>
  </div>
</div>

{% endblock %}

templates/landing_page/home.html
{% extends 'base.html' %}

<!-- SEO setting  -->
{% block seo %}


<title>Best Python Book for Beginners | Best 10 Book Store</title>
<meta name="description" content="You can find the best book list for Python programmers. Even you are Python beginner. We gather the best python books for you.">
<meta name="keywords" content="python books,beginners,best books, programming">


{% endblock %}
<!-- End of SEO setting  -->



{%block content%}

{% include 'items/jumbotron.html' %}

<div class="row top-buffer"></div>
{% include 'landing_page/product_navbar.html' %}

{% include 'featured_products/product_card.html' with item_list=featured_products %}


{% endblock %}

templates/landing_page/product_navbar.html
<div class="container-fluid">
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-lx-12">
        <br>
        <br>
   <h4 class="title-text">Featured Books For September</h4>
        <br>
 <ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link btn btn-outline-info btn-sm" href="?category=Startup"><span class="lead">Startup</span></a>
  </li>
  <li class="nav-item">
    <a class="nav-link btn btn-outline-info btn-sm" href="?category=Programming"><span class="lead">Programming</span></a>
  </li>
  <li class="nav-item">
    <a class="nav-link btn btn-outline-info btn-sm" href="?category=Investment"><span class="lead">Investment</span></a>
  </li>
</ul>
        <br>
        <br>
     <h5 class="title-text text-center">Top 10 book about"{{ category }}"</h5>
        <br>
</div>
    </div>


    </div>

templates/navbar.html
  <style>
 .base-nav {
    background-color: #FCEFE7;
    }

</style>
  <ul class="nav base-nav">

  <li class="nav-item">
    <a class="nav-link" href="{% url 'landing_page:home' %}" ><span class="h6 font-weight-light text-secondary">Best10</span></a>
  </li>
    <li class="nav-item ">
    <a class="nav-link" href="{% url 'blogs:list' %}"><span class="h6 font-weight-light text-secondary">Blogs</span></a>
  </li>
      <li class="nav-item">
    <a class="nav-link" href="{% url 'landing_page:contact'%}"><span class="h6 font-weight-light text-secondary">Contact</span></a>
  </li>
  </ul>